version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./backend/laravel/:/var/www
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react
    volumes:
      - ./frontend/react-app:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development